# Generated by Django 5.2.5 on 2025-08-30 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-discharge_date']},
        ),
        migrations.AddField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
